### ISSUE TITLE
How to enable dark mode in Facebook Messenger?

### ISSUE THREAD

**Issue by vurtomatic** [TheGoddessInari/hamsket#264]
Does anyone know?

Clicking on the three-dot more menu and selecting preference doesn't give the option. But Facebook Messenger on the web has dark mode.

**Comment by zanechua** [comment]
Dark mode is only available on facebook.com but not on messenger.com 

Currently using this set of custom css that I pulled from one of the chrome extensions (can't remember which one), fixed it after messenger updated the css selectors:

```css
html#facebook{overflow-y:hidden !important}._9dls{--card-background:#121212 !important;--comment-background:rgba(255, 255, 255, 0.1) !important;--disabled-button-background:rgba(255, 255, 255, 0.1) !important;--disabled-icon:rgba(132, 132, 132, 0.6) !important;--disabled-text:rgba(132, 132, 132, 0.6) !important;--divider:rgba(255, 255, 255, 0.17) !important;--filter-disabled-icon:brightness(0) invert(0.3) !important;--filter-placeholder-icon:brightness(0) invert(0.4) !important;--filter-primary-icon:brightness(0) invert(0.4) !important;--filter-secondary-icon:brightness(0) invert(0.4) !important;--hosted-view-selected-state:rgba(255, 255, 255, 0.08) !important;--highlight-bg:rgba(255, 255, 255, 0.1) !important;--hover-overlay:rgba(255, 255, 255, 0.1) !important;--media-inner-border:rgba(255, 255, 255, 0.17) !important;--media-outer-border:#000 !important;--messenger-card-background:#000 !important;--messenger-reply-background:#262626 !important;--overlay-alpha-80:rgba(0, 0, 0, 0.5) !important;--nav-bar-background-gradient:rgba(0, 0, 0, 0) !important;--placeholder-icon:#848484 !important;--placeholder-text:#848484 !important;--popover-background:#121212 !important;--positive-background:#121212 !important;--primary-deemphasized-button-background:rgba(255, 255, 255, 0.1) !important;--primary-deemphasized-button-pressed:rgba(255, 255, 255, 0.08) !important;--primary-deemphasized-button-pressed-overlay:rgba(255, 255, 255, 0.1) !important;--primary-deemphasized-button-text:--accent !important;--primary-icon:#d0d0d0 !important;--primary-text:#d0d0d0 !important;--secondary-button-background:rgba(255, 255, 255, 0.1) !important;--secondary-button-pressed:rgba(255, 255, 255, 0.08) !important;--secondary-button-text:#d0d0d0 !important;--secondary-icon:#848484 !important;--secondary-text:#848484 !important;--shadow-inset:rgba(255, 255, 255, 0.17) !important;--surface-background:#000 !important;--wash:#262626 !important;--web-wash:#121212 !important}._9dls ._1og-, ._9dls .hgaippwi, ._9dls .nwpbqux9{background-color:var(--card-background) !important}._9dls .n1jkxfxr{background-color:var(--secondary-button-background) !important}._9dls path[fill="#000"], ._9dls svg.hwsy1cff, ._9dls svg[fill="#000"]{fill:var(--secondary-text) !important}._9dls .oaz4zybt{box-shadow:none !important}._9dls .sp_Ak9mPwp2uaF_2x.sx_b00c79{filter:var(--filter-secondary-icon) !important}._9dls .bafdgad4{box-shadow:0 1px 0 var(--divider) !important}.rq0escxv.l9j0dhe7.du4w35lb.j83agx80.g5gj957u.rj1gh0hx.buofh1pr.hpfvmrgz.i1fnvgqd.bp9cbjyn.owycx6da.btwxx1t3.dflh9lhu.scb9dxdr.sj5x9vvc.cxgpxx05.sn0e7ne5.f6rbj1fe.l3ldwz01{display:none !important}
```

You can use it by going to Facebook service, click the wheel, advanced and custom css.
